[package]
name = "chip8"
version = "0.1.0"
authors = ["tikara <tikaradate@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
sdl2 = "0.34.3"
gl = "0.14.0"
